### PR TITLE
[Add] Display labels on polygons

### PR DESCRIPTION
**Pull request by dek-odoo**
# Description
Now user can see what each polygon is about.

zip polygons with labels

# Configuration:
- Need to tick "Display Labels on Polygon" field
- Select appropriate attribute field

configuration

Pleasure to help, changes are welcome.
[Demo video.](https://youtu.be/fzpLElJKEjA)

### CODE REVIEW

**Comment by dek-odoo** [comment]
@yvaucher @lmignon

**Review by yvaucher — APPROVED** [review]
Nice addition, LGTM

**Review by lmignon — APPROVED** [review]
LGTM but we must fix pylint before merging

**Comment by dek-odoo** [comment]
Hi @lmignon 
The Travis CI issues do not seem to be from my code.
Similar to [here](https://github.com/OCA/geospatial/pull/160#issuecomment-383087999)

**Review by ecino — APPROVED** [review]

**Pull request merged**
