### PR TITLE
 [13.0][MIG] base_geoengine 

### PR DESCRIPTION
**Pull request by tschanzt**

### CODE REVIEW

**Comment by tarteo** [comment]
Can you add these features / fixes also https://github.com/OCA/geospatial/pull/232

**Review by yvaucher — CHANGES_REQUESTED** [review]
Code LGTM

But those 2 commits can be merged and a better commit message would help.

https://github.com/OCA/geospatial/pull/219/commits/793759207d848f260d2592de48d5a668527995be
https://github.com/OCA/geospatial/pull/219/commits/7d0a6cbbe796e8a81d2d6fe516a5b04a78487129



Plus, you want this commit to fix runbot state:

https://github.com/OCA/geospatial/commit/1a04d3eefbc08c8f5eb4f77e69c284eebeaa3f75

**Review by yvaucher — APPROVED** [review]
LGTM Runbot is still failing, but I'll take care of that.

**Pull request merged**
