### PR TITLE
[14.0][FIX]base_geoengine: require Shapely<2

### PR DESCRIPTION
**Pull request by HekkiMelody**
#318 

Module will require refactoring to function with Shapely v2. For now, I've added documentation, instructions and a notice in the try/except around the import.

### CODE REVIEW

**Comment by NL66278** [comment]
@aleuffre Would any more changes required then replacing `asShape` with `shape`?

**Comment by HekkiMelody** [comment]
@NL66278 I do not know. The upgrade documentation mentions a bunch of things to potentially fix https://shapely.readthedocs.io/en/stable/migration.html , and I honestly didn't have time to look into it. Happy to close my PR in favour of another one that actually makes the module compatible with Shapely v2.

**Comment by NL66278** [comment]
@aleuffre As all tests run fine with replacing asShape with shape, I think this will be enough. I did not look at all the behavioral changes and what consequences that might have, but none of the other removed functions or attributes mentioned in the migration guide are used in 2.0.0.

**Comment by HekkiMelody** [comment]
Was being conservative since I didn't have much time to look into the issue, but sounds good to me. Closing in favour of #322 

Thank you @NL66278

**Comment by yvaucher** [comment]
Shapely break change seems quite recent, released on Dec 12, 2022, we could be nice an give a dedicated error message.
On the other hand shape is already available since shapely 1.8.0 released on Oct 22, 2021.

Sadly, external-dependencies in `__manifest__.py` doesn't allow a check on a minimal version.

**Comment by NL66278** [comment]
Actually shape has been available since 2008:
```
commit 7610854e7344d27c082f4c5f976d661380d1ebc3
Author: Sean Gillies <sean.gillies@gmail.com>
Date:   Mon Apr 28 03:01:30 2008 +0000

    Most users should use shape() instead of asShape()
    
    git-svn-id: http://svn.gispython.org/svn/gispy/Shapely/trunk@1087 b426a367-1105-0410-b9ff-cdf4ab011145

diff --git a/CHANGES.txt b/CHANGES.txt
index a673b16..86c0dc9 100644
--- a/CHANGES.txt
+++ b/CHANGES.txt
@@ -5,6 +5,7 @@ All tickets are children of http://trac.gispython.org/projects/PCL/ticket/
 - Disentangle Python and topological equality (#163).
 - Implement safe predicate shortcuts for objects identical in the Python sense
   (#163).
+- Add shape(), a factory that copies coordinates from a geo interface provider.
 
 1.0.3 (2008-04-09)
 ------------------
```

**Pull request closed without merging**
