### PR TITLE
[17.0][MIG] base_geoengine: Migration to 17.0

### PR DESCRIPTION
**Pull request by reichie020212**

### CODE REVIEW

**Comment by dreispt** [comment]
@reichie020212 I believe you missed the procedure to bring the fill commit history.
See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

**Comment by reichie020212** [comment]
> @reichie020212 I believe you missed the procedure to bring the fill commit history. See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

@dreispt full commit history is in this commit https://github.com/OCA/geospatial/pull/357/commits/ef6c9009252925a580247988cdb7f6d10e410699, I squash them using git rebase to reduce the commit noise

**Comment by dreispt** [comment]
@reichie020212 Got it. We want the full history, as it provides information on the changes dates, authors and reasons.
Only redundant commits, if any, need to be squashed.

**Comment by reichie020212** [comment]
> @reichie020212 Got it. We want the full history, as it provides information on the changes dates, authors and reasons. Only redundant commits, if any, need to be squashed.

@dreispt Ahh, I see. Noted on this. I'll update the PR.

**Comment by reichie020212** [comment]
> > @reichie020212 Got it. We want the full history, as it provides information on the changes dates, authors and reasons. Only redundant commits, if any, need to be squashed.
> 
> @dreispt Ahh, I see. Noted on this. I'll update the PR.

@dreispt commit history is now updated.

**Comment by reichie020212** [comment]
I encountered a javascript error when trying to access the geoengine view mode, I tried fixing it but to no avail. Can someone help me on this? Thank you.

**Comment by reichie020212** [comment]
in the latest commit, I fixed some issue and I think the only issue remaining is the error when trying to click the geo fields in the geoengine view mode.

**Comment by reichie020212** [comment]
Closing this PR for now since I modify the geoengine view mode based on our needs, will create a new PR on a later time.
below functionalities has been added in my latest commit
- added transparency field in vectors
- ability to modify the default zoom of the map in the UI
- added search engine in the geoengine view mode
- added opacity field to raster to modify its opacity in the map
- able to add and edit raster inside geoengine view mode

There are still some errors that needs to fix

**Pull request closed without merging**
