### PR TITLE
[12.0][fix] displaying relation fields in map info box - fixes #224

### LINKED ISSUE #224: [12.0] map_info_box shows '[object Object]' for related fields
This worked on 9.0 it doesn't on 12 (see screenshot)
Model:
```
 ...
class ProjectTaskMaps(models.Model):
    _inherit = 'project.task'
    _name = 'project.task'
    
    geo_point = fields.GeoPoint('Site coordinates', related='site_id.point')
... 
```
(site_id is a many2one in project.task relating to a sites table with geopoint field)

View:
```
...
    <record id="ir_ui_view_sites_task_maps_view" model="ir.ui.view">
        <field name="name">Tasks view</field>
        <field name="arch" type="xml">
            <geoengine version="7.0">
            	<field name="site_id"/>
                <field name="name"/>
                <field name="project_id"/>
                <field name="user_id"/>
                <field name="stage_id"/>
                <field name="geo_point"/>
            </geoengine>
        </field>
        <field eval="16" name="priority"/>
        <field name="model">project.task</field>
    </record>
...
```
snapshot2

I apologize if it's something obvious.... I'm slowly learning

### PR DESCRIPTION
**Pull request by alpham**
fixes #244

### CODE REVIEW

**Review by sciallo — COMMENTED** [review]
Works for me, fixes #224 (I don't find a #244) ... Colored filter seems to not be following values so I'm guessing there is another place this is happening too....

**Comment by alpham** [comment]
yes @sciallo this is true, I meant #224 .
the one reported by you, this is what this PR should fix.

**Comment by sciallo** [comment]
You're the man!

**Comment by yvaucher** [comment]
Seems you included the patch https://github.com/OCA/geospatial/pull/226

Let's keep them both separated to keep track of the fixes in the commit history.

I'll merge #226 and you will just have to rebase on branch 12.0

**Comment by yvaucher** [comment]
@alpham   Please also fix the comment to point to the right issue number with a `git commit --amend`

EDIT bad @ mention

**Comment by sciallo** [comment]
> @sciallo Please also fix the comment to point to the right issue number with a `git commit --amend`

@yvaucher I'm confused, I don't think I can, I didn't submit the PR... (forgive me if I'm not understanding, I'm still green to git)

**Comment by yvaucher** [comment]
@sciallo indeed my message was meant for @alpham (fixed)

**Comment by alpham** [comment]
@yvaucher done

**Pull request merged**
