### PR TITLE
HTTP URIs not compatible with HSTS #40

### PR DESCRIPTION
**Pull request by lasley**
- updated js.mapbox theme URI to relative scheme and their Cloudfront address so that SSL cert is valid
- updated Google maps URI to relative scheme

re #40

### CODE REVIEW

**Comment by lasley** [comment]
Hrmm that's a cryptic TravisCI error. Anyone have a suggestion here?

**Comment by lmignon** [comment]
@dlasley Travis error is unrelated. :+1: (tested on runbot) If not already done, you also need to sign a CLA. see  http://odoo-community.org/page/website.cla

**Comment by lasley** [comment]
Thanks @lmignon - CLA is submitted and verified :smile:

**Comment by lasley** [comment]
Hi All - I have quite a few updates that I'm working on, and I'd like to submit PRs on them as well ( https://github.com/OCA/geospatial/compare/8.0...laslabs:8.0 - not fully complete). Should I just kill this PR in favor of a new one that contains (allthethings)?

I will also be looking at adding a Google Maps geocoder (and abstracting the current). Would you mind letting me know any challenges that you ran into, aside from the obvious non-free factor?

**Comment by lmignon** [comment]
@dlasley IMO, It is better to make another PR for the other changes. This PR concern a correction while you adds new functionnalities in https://github.com/OCA/geospatial/compare/8.0...laslabs:8.0
Google Maps Geocoder is not free and you can't store values provided by google in your database. (see #34 and https://github.com/OCA/geospatial/issues/32 ) You can provide your own geocoder by overriding the function ResPartner.geocode_address in an other module (https://github.com/OCA/geospatial/blob/8.0/geoengine_base_geolocalize/models/res_partner.py#L42)
I works on the migration to ol3 in a dedicated branch  (slowly since I do it during my free times) https://github.com/acsone/geospatial/tree/8.0-ol3-lmi. It seems it will not be possible to keep google as tile providers and I plan to drop google from the list of available raster_type you can choose to display your map (The issue with google is summarized in  https://github.com/openlayers/ol3/issues/2205)

@nbessi @bwrsandman any comments on this PR? It's a little fix and it would be nice to have it merged quickly.

**Comment by lasley** [comment]
@lmignon - Thanks for the info. Crap, I completely forgot about the Google API restrictions, and it seems like you've thoroughly evaluated this, so I'll just drop that thought altogether. 

I'll be finalizing my other additions in the next few days, and will submit another PR for them. 

Re Ol3, want help? I have literally zero experience with OpenLayers, but I'm sure I can figure it out.

**Comment by bwrsandman** [comment]
@lmignon Sorry. I am not qualified to make a good review in javascript. I did see that travis is failing and that would block the PR being merged quickly.

I have restarted the tests in case.

**Comment by lmignon** [comment]
@bwrsandman Thank you for the review. Travis fails since one of the patch we try to apply in travis.yml has been merged in Odoo https://github.com/odoo/odoo/pull/5618 (but not yet in OCB).  https://github.com/OCA/geospatial/pull/44 try to fix travis

**Comment by nbessi** [comment]
@lmignon seems ok with me but I asked @fredj to do a review too.

**Comment by fredj** [comment]
Looks good to me

**Comment by lmignon** [comment]
in short:  3  :+1: 
This one can be merged

**Comment by nbessi** [comment]
@lmignon before merging I would prefer to fix travis. 
I'm back from holidays I will not have time this week, can you take care of this else it will be for next week.

**Comment by nbessi** [comment]
@lmignon I did not see https://github.com/OCA/geospatial/pull/44 state. Thanks for the patch, I relauched the build of #44 let's hope it is green now.

**Comment by lasley** [comment]
Bah that's what I get for changing my name :P CLA submitted.

Merged in the changes from 8.0 to this branch. Looks like tests are now passing

**Pull request merged**
