### PR TITLE
[MIG][14.0] Migrated web widget google marker icon picker.

### PR DESCRIPTION
**Pull request by AmmarOfficewalaSerpentCS**
depends #291

### CODE REVIEW

**Comment by AmmarOfficewalaSerpentCS** [comment]
@smangukiya , @murtuzasaleh 
Can you please review this PR?

**Comment by AmmarOfficewalaSerpentCS** [comment]
@max3903 , @dreispt , 
Can you please review this PR ?

**Comment by dreispt** [comment]
Fix Travis please

**Comment by AmmarOfficewalaSerpentCS** [comment]
@dreispt ,
This module depends on a #291

**Comment by AmmarOfficewalaSerpentCS** [comment]
@dreispt , @max3903 , 

Travis Green now

**Review by max3903 — APPROVED** [review]

**Pull request merged**
