### PR TITLE
[17.0][MIG] base_geoengine_demo: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 154489
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

- [Issue] https://github.com/OCA/geospatial/issues/349

Depends on:

- [base_geoengine] https://github.com/OCA/geospatial/pull/368

### CODE REVIEW

**Review by miquelalzanillas — APPROVED** [review]
Tested functionally. LGTM.

**Comment by miquelalzanillas** [comment]
> Tested functionally. LGTM.

Sorry but I didn't tested following the 'base_geoengine_demo' readme and trying to follow those indications still are some bugs.

**Comment by peluko00** [comment]
It's ready to be merge @dreispt

**Comment by dreispt** [comment]
@peluko00 Can you please rebase on latest 17.0, and ensure that that last Merge commit is not in the history?

**Comment by peluko00** [comment]
> @peluko00 Can you please rebase on latest 17.0, and ensure that that last Merge commit is not in the history?

Done, thanks! Now it's ready

**Comment by peluko00** [comment]
It's ready to merge @yvaucher

**Comment by yvaucher** [comment]
Indeed I saw the red mark but it's only the coverage. Thanks .

**Pull request merged**
