### PR TITLE
12.0 ref use addons repo template + travis -> github

### PR DESCRIPTION
**Pull request by legalsylvain**

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @OCA/geospatial-maintainers and @OCA/community-maintainers 

could you take a look on that PR ? 
- I switch from obsolete travis to github CI.
- I fixed CI. (Travis is red for the time being on V12 branch)

Note : I replace ``postgres/postgres:9.6`` by ``postgis/postgis:9.6-3.2`` and it seems to make the job.

Note : @yvaucher maybe you could take a look on this one. I see that you disabled the CI for the V13 branch here. https://github.com/OCA/geospatial/commit/6adf14cfb68a991312ff657c360865ba5e6ffb4a

kind regards.

**Comment by legalsylvain** [comment]
@lmignon, @yvaucher : could you take a little time to review and to merge quickly this PR ? 

- CI is obsolete on 12.0 (Travis, instead of Github action)
- Current 12.0 branch is red, so new PR are marked as red.
- it is not possible to use pre-commit stuff.

thanks !

**Comment by legalsylvain** [comment]
No answer from maintainers.

@sbidoul : could you take a look on this one. (see your mail "Phasing out Travis", sent today).

**Review by lmignon — APPROVED** [review]

**Pull request merged**
