### PR TITLE
[10.0] [ADD] geoengine_location: Add module.

### PR DESCRIPTION
**Pull request by woodbrettm**
WIP atm
- [x] Depends #150

### CODE REVIEW

**Comment by woodbrettm** [comment]
heya @lasley I'm having some issues with getting this geo_point field to work. The tests are saying it doesn't exist in the database.
https://travis-ci.org/OCA/geospatial/jobs/263720134#L642

**Comment by lasley** [comment]
@bmw95 - Yeah I'm not so sure about Travis in this repo. It looks broken on all the master builds, although for doc issues, so I don't even know if it's failing on the same thing as your's.

I'd assume POSTGIS isn't setup properly or something. Just go off of your local testing I guess.

**Comment by lmignon** [comment]
@bmw95 A bug into geo_model prevents the creation of the column for computed geo fields... https://github.com/OCA/geospatial/pull/150/files#diff-758bcd153189712715dfd56ddc0c293dR45

**Comment by woodbrettm** [comment]
hmm @lasley @lmignon I wonder if the issue is that I haven't set it up properly. I removed the _compute attribute from the geo_point field and just have it as a regular field [here](https://github.com/LasLabs/geospatial/blob/0131a7be7779c09dbd73b383639cc625eb370a72/geoengine_location/models/res_better_zip.py#L14). 

When I run tests, I get an error that shows that the geo_point column does not exist in res.better.zip.

I did the following to set everything up:
```
in sql: ALTER USER odoo WITH SUPERUSER;
sudo apt-get install postgis
sudo /opt/odoo/_venv/bin/pip install simplejson
sudo /opt/odoo/_venv/bin/pip install geojson
sudo /opt/odoo/_venv/bin/pip install shapely
```

base_geoengine seemed to work fine.

**Comment by yvaucher** [comment]
@woodbrettm This PR needs a rebase

**Comment by woodbrettm** [comment]
Hi @yvaucher I'm not contributing anymore, so feel free to take over the PR :)

**Pull request closed without merging**
