### PR TITLE
[12.0] fix web view leaflet mal readme

### PR DESCRIPTION
**Pull request by legalsylvain**

### CODE REVIEW

**Comment by legalsylvain** [comment]
/ocabot merge patch

Fastracking.

**Comment by legalsylvain** [comment]
Annoying. 

This trivial PR failed, because of an error in ``geoengine_base_geolocalize``.



```
2023-05-16 08:06:44,925 252 INFO odoo odoo.addons.geoengine_base_geolocalize.tests.test_geoengine_partner: test_geo_localize (odoo.addons.geoengine_base_geolocalize.tests.test_geoengine_partner.TestGeoenginePartner) 
2023-05-16 08:06:45,737 252 ERROR odoo odoo.addons.geoengine_base_geolocalize.tests.test_geoengine_partner: FAIL 
2023-05-16 08:06:45,737 252 INFO odoo odoo.addons.geoengine_base_geolocalize.tests.test_geoengine_partner: test_get_geo_point (odoo.addons.geoengine_base_geolocalize.tests.test_geoengine_partner.TestGeoenginePartner) 
2023-05-16 08:06:45,776 252 INFO odoo odoo.addons.geoengine_base_geolocalize.tests.test_geoengine_partner: ====================================================================== 
2023-05-16 08:06:45,776 252 ERROR odoo odoo.addons.geoengine_base_geolocalize.tests.test_geoengine_partner: FAIL: test_geo_localize (odoo.addons.geoengine_base_geolocalize.tests.test_geoengine_partner.TestGeoenginePartner) 
2023-05-16 08:06:45,777 252 ERROR odoo odoo.addons.geoengine_base_geolocalize.tests.test_geoengine_partner: Traceback (most recent call last): 
2023-05-16 08:06:45,777 252 ERROR odoo odoo.addons.geoengine_base_geolocalize.tests.test_geoengine_partner: `   File "/__w/geospatial/geospatial/geoengine_base_geolocalize/tests/test_geoengine_partner.py", line 41, in test_geo_localize 
2023-05-16 08:06:45,777 252 ERROR odoo odoo.addons.geoengine_base_geolocalize.tests.test_geoengine_partner: `     "Longitude Should be equals", 
2023-05-16 08:06:45,777 252 ERROR odoo odoo.addons.geoengine_base_geolocalize.tests.test_geoengine_partner: ` AssertionError: 5.41191 != 5.40539 within 2 places : Longitude Should be equals 

```

**Comment by yvaucher** [comment]
Let me try

/ocabot merge patch

**Pull request merged**
