### PR TITLE
Fix wrong autoinstall key in geoengine_base_geolocalize

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by guewen** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1: Why the Travis and runbot errors?

**Comment by lmignon** [comment]
Travis is red because the patch is no more required https://github.com/OCA/geospatial/blob/8.0/.travis.yml#L33
:+1:

**Comment by pedrobaeza** [comment]
Can you please change .travis.yml then?

**Comment by lmignon** [comment]
@pedrobaeza https://github.com/OCA/geospatial/pull/84

**Pull request merged**
