### PR TITLE
[MIG] base_google_map: Migration to 13.0

### PR DESCRIPTION
**Pull request by brian10048**

### CODE REVIEW

**Comment by brian10048** [comment]
@yvaucher - There is the same error here as well https://travis-ci.com/github/OCA/geospatial/jobs/489824581#L581

**Comment by yvaucher** [comment]
https://github.com/OCA/geospatial/pull/287/checks?check_run_id=2327638791

The lint is now under github actions, it's just missing some formating of one file and we can merge

(running pre-commit should auto format the file for you)

**Review by yvaucher — APPROVED** [review]

**Comment by brian10048** [comment]
Thank you @yvaucher - I ran pre-commit on this module.  Looks like there are some files in other modules that are causing lint to fail

**Comment by yvaucher** [comment]
@brian10048 IIRC correcly the pre-commit on travis was run only on the changes. Thanks for the lint fixing PR. #294

**Pull request closed without merging**
