### PR TITLE
[UPDATE] Add rtl ignore for persian and arabic language

### PR DESCRIPTION
**Pull request by Sanazzzmi**
related issue
https://github.com/OCA/geospatial/issues/388

### CODE REVIEW

**Review by mostafabarmshory — APPROVED** [review]

**Review by fardinmardani — APPROVED** [review]

**Comment by Sanazzzmi** [comment]
@legalsylvain 
@wouitmil

 I need these changes. Thank you for merging faster. thank you very much.

**Comment by legalsylvain** [comment]
Hi @Sanazzzmi. 
- I never touched the module ``base_geoengine`` and I have no idea how to test it.
- I don't know anything about the specifics of developing ‘RTL’-type languages.

CC : @OCA/geospatial-maintainers

**Comment by mostafabarmshory** [comment]
Dear @OCA/geospatial-maintainers

Would you please check this PR?

**Comment by Sanazzzmi** [comment]
in this [link](https://odoo-community.org/psc-teams/geospatial-23) i find you.
@lmignon @yvaucher
please merge this rp. i need it.
thank you very much.

**Review by lmignon — APPROVED** [review]

**Pull request merged**
