### PR TITLE
[14.0][MIG] base_geoengine

### PR DESCRIPTION
**Pull request by Urvisha-OSI**
Base Geoengine module migration in v14

### CODE REVIEW

**Review by max3903 — APPROVED** [review]

**Comment by Freni-OSI** [comment]
@yvaucher , Can you please review this PR?
cc: @max3903

**Comment by Freni-OSI** [comment]
@yvaucher Can you please review this? It needs to be merged ASAP.

**Comment by nikul-serpentcs** [comment]
@Urvisha-OSI Thanks for this. Could you please follow the migration guide?  
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

Here preserve history (previous version commit history) missing in this PR. 
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch

CC @max3903

**Comment by Urvisha-OSI** [comment]
> @Urvisha-OSI Tahnks for this. Could you please follow the migration guide? https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0
> 
> Here preserve history (previous version commit history) missing in this PR. https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch
> 
> CC @max3903

**Comment by yvaucher** [comment]
This is missing the full history of commits of the module
https://github.com/OCA/geospatial/commits/14.0/base_geoengine

Please next time follow the contributor guidlines
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0

**Comment by yvaucher** [comment]
@max3903 you shouldn't have merged this :disappointed:

**Pull request merged**
