### PR TITLE
[14.0][MIG] web_view_google_map

### PR DESCRIPTION
**Pull request by AmmarOfficewalaSerpentCS**
depends #290

### CODE REVIEW

**Comment by AmmarOfficewalaSerpentCS** [comment]
@smangukiya , @murtuzasaleh , @brian10048 , 

Can you please review this PR?

**Comment by brian10048** [comment]
@AmmarOfficewalaSerpentCS can you rebase your branch since the dependent module is now merged? I can review and test on the runbot build

**Comment by osi-scampbell** [comment]
@AmmarOfficewalaSerpentCS after you rebase your branch with the dependency, let's make the Travis checks green so we can merge this. Thanks!

**Review by max3903 — APPROVED** [review]

**Comment by max3903** [comment]
@Urvisha-OSI Please fix this PR.

**Pull request merged**
