### PR TITLE
first i18n

### PR DESCRIPTION
**Pull request by eric-lemesre**
initial i18n for module 
- base_geoengine
-  base_geoengine_demo
- geoengine_base_geolocalize
- geoengine_partner

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Don't include pot files.

You should also sign the OCA CLA: https://odoo-community.org/page/cla

Another option is to enable the translation on Transifex.

**Comment by eric-lemesre** [comment]
@pedrobaeza I don't know how to enable Transifex. Do you have links to learn about this? 

I am new on github and i don't know how to update pull request for deletion *.pot. An other pull request?

**Comment by eric-lemesre** [comment]
close by nistake

**Comment by eric-lemesre** [comment]
close by mistake

**Comment by eric-lemesre** [comment]
I have an account in OCA "Eric Lemesre" but i can't update my profile with my github account eric-lemesre

**Comment by yvaucher** [comment]
Transifex added for 8.0 in https://github.com/OCA/geospatial/pull/30

**Comment by yvaucher** [comment]
I edited your OCA account to set the github account but I couldn't find the CLA signed if it has already been done, maybe it hasn't been reveived it yet.

**Pull request closed without merging**
