### PR TITLE
[ADD] base_geolocalize_company

### PR DESCRIPTION
**Pull request by legalsylvain**
Trivial Module.

This module extends the ``base_geolocalize`` odoo module, to add Geolocalization on Companies (``res.company``) level.

It adds a new tab named 'Company Assignation' and allow to enter manually (or automatically via the 'Geolocate' button) latitude and longitude.

This module is only useful in a multi-company context.

res_company_form

Usefull to use the new module ``web_view_leafltet_map``. (https://github.com/OCA/geospatial/pull/310)

Note : Travis is failing because 12.0 is red. Please review : https://github.com/OCA/geospatial/pull/311

### CODE REVIEW

**Review by quentinDupont — APPROVED** [review]

**Review by hparfr — APPROVED** [review]

**Comment by yvaucher** [comment]
@legalsylvain can you solve the lint?

```
base_geolocalize_company/models/res_company.py:11:89: E501 line too long (141 > 88 characters)
base_geolocalize_company/models/res_company.py:12:89: E501 line too long (144 > 88 characters)
base_geolocalize_company/models/res_company.py:13:62: E231 missing whitespace after ','
base_geolocalize_company/models/res_company.py:13:89: E501 line too long (130 > 88 characters)
base_geolocalize_company/models/res_company.py:16:1: W391 blank line at end of file
```

**Comment by legalsylvain** [comment]
@dreispt, @yvaucher : all is green. Can be merged.

**Pull request merged**
