### PR TITLE
Add meta files from maintainer-quality-tools

### LINKED ISSUE #18: Setup travis on 8.0 branch

### PR DESCRIPTION
**Pull request by bwrsandman**
Ignore OSX Files temp files in source
Add License file
Add travis and coverage badges

Closes #18

### CODE REVIEW

**Comment by bwrsandman** [comment]
If I remember correctly, an extension needs to be added to the postgresql database, could someone provide this info for me?

**Comment by lmignon** [comment]
@bwrsandman I've done the same work in the 7.0-migrate-from-6.1 branch and fixed the code to install the extension in the database

**Comment by bwrsandman** [comment]
@lmignon thanks for pointing that out.

**Comment by guewen** [comment]
:+1:

**Comment by yvaucher** [comment]
Those are already in https://github.com/OCA/geospatial/pull/24

Thus I close this one

**Pull request closed without merging**
