### PR TITLE
[9.0] extraction geoengine swisstopo

### PR DESCRIPTION
**Pull request by yvaucher**
Following #72 changes

### CODE REVIEW

**Comment by lmignon** [comment]
@yvaucher a rebase is needed.

**Comment by yvaucher** [comment]
rebased

**Comment by guewen** [comment]
```
  File "/home/travis/build/OCA/geospatial/geoengine_swisstopo/__init__.py", line 4, in <module>

    from . import models

ImportError: cannot import name models
```

seems that `geoengine_swisstopo/models/__init__.py` is missing

**Comment by yvaucher** [comment]
@guewen Indeed I added the missing file

**Pull request merged**
