### PR TITLE
[MIG] base geoengine to 12.0

### PR DESCRIPTION
**Pull request by yvaucher**
Only few changes are required to make it work.

I'll push the portage of base_geoengine_demo in another PR

### CODE REVIEW

**Comment by fredj** [comment]
@oca-clabot CLA sent

**Review by asaunier — APPROVED** [review]
Looks good to me.

Travis reports errors but are they really related to the changes suggested here?

Is there still work in progress?
Please note these extra changes I would like to push to this PR in order to add Swisstopo baselayers support: https://github.com/yvaucher/geospatial/pull/5

**Comment by fredj** [comment]
@oca-clabot Good boy!

**Comment by murtuzasaleh** [comment]
@yvaucher Can you please make Travis green.

**Comment by yvaucher** [comment]
@murtuzasaleh travis should get green soon.

**Comment by yvaucher** [comment]
Still some issues with runbot, nevertheless Travis now is green.

**Pull request merged**
