### PR TITLE
[12.0][FIX] base_geoengine. use shape() instead of asShape()

### PR DESCRIPTION
**Pull request by NL66278**
The method asShape has been removed from shapely.geometry and should be replaced by shape.

### CODE REVIEW

**Comment by NL66278** [comment]
@lmignon Laurent would you have a look at this please?

**Review by lmignon — CHANGES_REQUESTED** [review]
@NL66278 Thank you for the fix. In the same time, you should also modify https://github.com/OCA/geospatial/blob/12.0/setup/base_geoengine/setup.py to add a dependency override to specify a constraint on the expected version for the shapely lib...

```python
import setuptools

setuptools.setup(
    setup_requires=['setuptools-odoo'],
    odoo_addon={
        'external_dependencies_override': {
            'python': {
                'shapely': 'shapely>=?.?.?'
            },
        },
    }
)
```

**Comment by NL66278** [comment]
@lmignon Is that really needed, as the alternative `shape()` function has been available since 2008, so this should work on both older and newer versions.

**Review by lmignon — APPROVED** [review]

**Review by mathben — APPROVED** [review]
I tested with my other module, all works, thank you!

**Pull request merged**
