### PR TITLE
[IMP] PR odoo/odoo#5618 is merged in Odoo

### PR DESCRIPTION
**Pull request by lmignon**
Strange, tests fails on OCB...

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I suppose because the patch is not yet propagated to OCB...

**Comment by nbessi** [comment]
:+1:  let's rerun the travis and see if it is green

**Comment by nbessi** [comment]
Travis restarted

**Comment by nbessi** [comment]
ouch OCB still red

**Comment by lmignon** [comment]
@nbessi Yes OCB fails :cry: I need to run the tests manually with OCB to check what's wrong.

**Comment by lmignon** [comment]
@nbessi green!

**Comment by nbessi** [comment]
:+1: Seems ok I think we can fast track it

**Comment by nbessi** [comment]
thanks @lmignon :smile:

**Comment by guewen** [comment]
:+1:

**Pull request merged**
