### PR TITLE
[9.0] [FIX] base_geoengine: correct arguments for fields_view_get

### PR DESCRIPTION
**Pull request by NL66278**
When installing base_geoengine and then geoengine_partner you will, without this PR, get an exception like so:

```
Odoo Server Error
Traceback (most recent call last):
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/http.py", line 659, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/http.py", line 332, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/http.py", line 325, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/http.py", line 975, in __call__
    return self.method(*args, **kw)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/http.py", line 525, in response_wrap
    response = f(*args, **kw)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/addons/web/controllers/main.py", line 1174, in load
    action = request.session.model(action_type).read([action_id], False, ctx)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/http.py", line 1080, in proxy
    result = meth(cr, request.uid, *args, **kw)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/addons/base/ir/ir_actions.py", line 370, in read
    results = super(ir_actions_act_window, self).read(cr, uid, ids, fields=fields, context=context, load=load)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/models.py", line 3209, in read
    result = BaseModel.read(records, fields, load=load)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/models.py", line 3244, in read
    self._read_from_database(stored, inherited)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/models.py", line 3435, in _read_from_database
    res2 = self._columns[f].get(cr, self._model, ids, f, user, context=context, values=result)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/osv/fields.py", line 1506, in get
    result = self._fnct(obj, cr, uid, ids, name, self._arg, context)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/addons/base/ir/ir_actions.py", line 312, in _search_view
    'search', context=context)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/geospatial/base_geoengine/geo_model.py", line 143, in fields_view_get
    context=context, toolbar=toolbar, submenu=submenu)
  File "/home/openeyedev/var/projects/spinpompen_9011/odoo/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
TypeError: fields_view_get() got an unexpected keyword argument 'uid' 
```

### CODE REVIEW

**Comment by gfcapalbo** [comment]
LGTM, solves described bug.

**Comment by NL66278** [comment]
Build has two warnings, which are irrelevant to this PR. And most travis jobs success, except for the one building documentation. Solving that is also out of scope for this PR.

**Comment by gfcapalbo** [comment]
Fix solved described bug , :+1:

**Review by gfcapalbo — APPROVED** [review]
Fix solved described bug , :+1:

**Review by yvaucher — APPROVED** [review]

**Comment by yvaucher** [comment]
Something nasty happens in the CI but it is not related to this PR.

```
Recursion error:

maximum recursion depth exceeded
```

**Pull request merged**
