### PR TITLE
[MIG] base_geoengine 15

### PR DESCRIPTION
**Pull request by shurshilov**
[MIG] base_geoengine 15

### CODE REVIEW

**Comment by NL66278** [comment]
@shurshilov Please use the migration method that keeps the commit history: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

**Review by NL66278 — CHANGES_REQUESTED** [review]
Need to follow the standard migration method for OCA modules. Also note that the asShape method has been deprecated and must be replaced.

**Comment by yvaucher** [comment]
Warning the v14 was not migrated properly, thus we have to redo it from v13 and take additional commits from https://github.com/OCA/geospatial/pull/316

**Review by yvaucher — CHANGES_REQUESTED** [review]
Missing git history

**Comment by yvaucher** [comment]
Please refer to #326

**Pull request closed without merging**
