### PR TITLE
[16.0][mig] web_view_leaflet_map and web_view_leaflet_map_partner

### PR DESCRIPTION
**Pull request by legalsylvain**
- Trivial port of the modules : ``web_view_leaflet_map`` and ``web_view_leaflet_map_partner``

- mig commit to review : https://github.com/OCA/geospatial/pull/342/commits/1e873b609579f85f8520dfd5da6668c8353931b6

- bump leaflet lib from 1.8.0 , released on April 18, 2022 to 1.9.4, released on May 18, 2023.

res_partner_map

### CODE REVIEW

**Comment by PaulGoubert** [comment]
Hello @legalsylvain and thank you for this PR.     
FYI,  doing a functionnal review, and this working fine til trying to "group by" where I've an error "Uncaught Promise > Cannot read properties of undefined (reading 'lat')"

**Comment by legalsylvain** [comment]
hi @PaulGoubert . Nice catch ! 
I disabled the button "group by" (that makes no sense in a map context).

Could you test again, and update your review ?

thanks !

**Comment by PaulGoubert** [comment]
LGTM.  Thank you @legalsylvain

**Review by PaulGoubert — APPROVED** [review]
Functional Review OK.

**Review by navarrorico — COMMENTED** [review]
LGTM :ok_hand:

**Review by navarrorico — APPROVED** [review]

**Comment by legalsylvain** [comment]
geospacial maintainers : could you merge this one ? Thanks ! 
@yvaucher, @lmignon

**Comment by pedrobaeza** [comment]
Merging due to existing reviews:

/ocabot merge nobump

**Pull request merged**
