### PR TITLE
[16.0][FIX] geospatial_partner - error message on no partner with valid geom

### PR DESCRIPTION
**Pull request by wouitmil**
Added two fixes to avoid error message when no partners are encoded with a valid geo_point.

1. The check extent !== infinite_extent wasn't working as it's not a recommended way to compare arrays in javascript.
2. the filter in the right panel wasn't working if no partners are in the list

Added the geoengine view in the default contacts/resp_partner action

### CODE REVIEW

**Review by cyrilmanuel — APPROVED** [review]
LGTM until pre-commit fix

**Comment by wouitmil** [comment]
> LGTM until pre-commit fix

I'll try to fix it. It may be caused by a working syntax (optional chaining) that is not accepted by this version of eslint. Is it possible that the version is too old?

I see [here](https://github.com/eslint/eslint/issues/13566) that it's should be fixed since eslint v7.9.0 (and I see that the version used is v8.24.0)

**Comment by wouitmil** [comment]
> LGTM until pre-commit fix

Fixed ;-)

**Review by yvaucher — APPROVED** [review]

**Comment by yvaucher** [comment]
Can you improve the commit message `[FIX] base_geoengine & geospatial_partner `

Question to answer is: What do you fix in those modules?

**Pull request closed without merging**
