### PR TITLE
[16.0][MIG] - geoengine_base_geolocalize

### PR DESCRIPTION
**Pull request by sbejaoui**
needs:

- #328 
- #331

### CODE REVIEW

**Review by lmignon — CHANGES_REQUESTED** [review]
@sbejaoui This PR is missing https://github.com/OCA/geospatial/pull/155 and is very important to split addons and implement inverse on the latitude and longitude

**Comment by lmignon** [comment]
@sbejaoui do you plan to also migrate [base_geolocalize_openstreetmap](https://github.com/OCA/geospatial/tree/10.0/base_geolocalize_openstreetmap)?

**Review by lmignon — APPROVED** [review]
LGTM (Code + functional)

**Comment by IT-Ideas** [comment]
@lmignon , @sbejaoui  The PR is closed. Does it still need review?
LGTM. I am just unsure we need to update the Odoo server version in the `.pot` file.

**Comment by lmignon** [comment]
@IT-Ideas Thank you for reminder.... this PR has disappeared from my radar. I took the liberty to rebase it and I'll merge-it.

**Pull request merged**
