### PR TITLE
17.0: Migration for web_leaflet_lib

### PR DESCRIPTION
**Pull request by drkpkg**
Migrated library for 17.0.
Related PR: https://github.com/OCA/web/pull/2953

This library will be used as independent module and library for Leaflet.
The new Map field uses this lib, so the migration to 17.0 is needed.

### CODE REVIEW

**Comment by yvaucher** [comment]
Hello @drkpkg ,

It seems the history was not preserved correctly.
Please follow the guideline here https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

**Comment by legalsylvain** [comment]
Superseded by #383

**Comment by lmignon** [comment]
closing since it's superseded by #383

**Pull request closed without merging**
