### PR TITLE
[17.0][MIG] geoengine_partner: Migration to 17.0

### PR DESCRIPTION
**Pull request by peluko00**
Module migrated to version 17.0

cc https://github.com/APSL 155231
@miquelalzanillas @lbarry-apsl @javierobcn @mpascuall please review

- [Issue] https://github.com/OCA/geospatial/issues/349

Depends on:

- [ base_geoengine] https://github.com/OCA/geospatial/pull/368

### CODE REVIEW

**Review by mpascuall — APPROVED** [review]
Works good, checked in runboat

**Review by lbarry-apsl — APPROVED** [review]
LGTM, It works well

**Comment by peluko00** [comment]
@dreispt Seems it's ready to be merge

**Pull request merged**
