### PR TITLE
[8.0] Fix quantil repartition when there are less item than classes

### LINKED ISSUE #62: [8.0] [9.0] geoengine_demo: TypeError: bin.upperBound is undefined on some search
In demo data, when doing a search by code on retail machines it can raise the following javascript error:

Tested on port of 9.0 and on 8.0

To reproduce:
Open retails machine geoengine view.

Do a search on `3` -> 9 results it works
Do a search on `4` -> 4 results it fails
Do a search on `7` -> 4 results it fails
Remove code 37 do a search on `7`-> 3 results it fails
Remove code 27 do a search on `7` -> 2 results it passes

```
TypeError: bin.upperBound is undefined

http://localhost:8501/base_geoengine/static/src/js/mapfish/GeoStat.js:351
Traceback:
mapfish.GeoStat.Distribution<.defaultLabelGenerator@http://localhost:8501/base_geoengine/static/src/js/mapfish/GeoStat.js:351:16
mapfish.GeoStat.Distribution<.classifyWithBounds@http://localhost:8501/base_geoengine/static/src/js/mapfish/GeoStat.js:383:29
mapfish.GeoStat.Distribution<.classifyByQuantils@http://localhost:8501/base_geoengine/static/src/js/mapfish/GeoStat.js:415:16
mapfish.GeoStat.Distribution<.classify@http://localhost:8501/base_geoengine/static/src/js/mapfish/GeoStat.js:452:30
mapfish.GeoStat.Choropleth<.setClassification@http://localhost:8501/base_geoengine/static/src/js/mapfish/GeoStat/Choropleth.js:141:31
GeoengineView<.createVectorLayer@http://localhost:8501/base_geoengine/static/src/js/views/geoengine_view.js:230:13
GeoengineView<.createVectorLayers/<@http://localhost:8501/base_geoengine/static/src/js/views/geoengine_view.js:299:22
_.forEach@http://localhost:8501/web/static/lib/underscore/underscore.js:145:9
```

Tracing it a bit it seams it fails on `geostat.setClassification()` when it calls a method `classify` it passes `this.numClasses` as `nbBins` with a value of 5 for 4 items. Then it does a strange
 `var binSize = Math.round(this.values.length / nbBins);`

Which will round to 5, thus looping to compute bounds, it tries to take in account the bound of an non existing 5th object, and fail.

### PR DESCRIPTION
**Pull request by yvaucher**
Fixes #62

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Same comments as in 7.0.

**Comment by lmignon** [comment]
:+1: same as 7.0

**Comment by pedrobaeza** [comment]
:+1:

**Comment by fredj** [comment]
+1

**Comment by lmignon** [comment]
@yvaucher do you know why runbot fails? I'm not able to access to the build log.

**Comment by yvaucher** [comment]
@lmignon No idea, I just tried to force a rebuild

I doubt it has anything to do with this PR

@gurneyalex any idea why runbot don't provide logs ?

**Comment by lmignon** [comment]
@yvaucher  IMO, it's safe to merge your changes since they are not related to python code. What do you think?

**Comment by yvaucher** [comment]
@lmignon I agree, you can even see that the runbot fails on trivial changes such as #66

**Comment by lmignon** [comment]
@yvaucher OK I merge

**Comment by yvaucher** [comment]
Thanks

**Pull request merged**
