### PR TITLE
[17.0][MIG] web_leaflet_lib

### PR DESCRIPTION
**Pull request by legalsylvain**
Trivial migration.

Commit to review : https://github.com/OCA/geospatial/pull/383/commits/c570d6028313d89122841471471f596eaa22fda2

- to be used by https://github.com/OCA/web/pull/2953
- supersed : https://github.com/OCA/geospatial/pull/381

### CODE REVIEW

**Comment by weinni2000** [comment]
@legalsylvain:
Did you also already convert web_view_leaflet_map to 17/18?
Because otherwise I would like to contribute to that. There is already a demo project in OWL2 from AJScript
https://github.com/ajscriptmedia/odoo-map-view-type/tree/model-arch-parser
Do you know who is the maintainer of geospatial because I need help on the PR for the base geoengine migration to 18.

**Comment by legalsylvain** [comment]
Hi @weinni2000. 

- I didn't planned to migrate web_view_leaflet_map in v17 / V18. Feel free to do it. (I'm working on v16, and the next version I'll work is version 20).
- You can find who are the maintainers of the geospatial repo here : https://github.com/OCA/repo-maintainer-conf/blob/master/conf/psc/geospatial.yml. CC : @lmignon, @yvaucher 

regards.

**Review by yvaucher — APPROVED** [review]

**Comment by yvaucher** [comment]
@weinni2000 Noone volunteered to migrate `web_view_leaflet_map` yet, contributions are welcome
If you do so please leave a note in one of those issues:
in 17.0 https://github.com/OCA/geospatial/issues/349
in 18.0 https://github.com/OCA/geospatial/issues/379

**Comment by legalsylvain** [comment]
Hi. could we merge this trivial one to unblock : https://github.com/OCA/web/pull/2953

thanks !

**Comment by legalsylvain** [comment]
@lmignon could you retry ? 
the error is related to an error in a call of an unmocked external API.
see : https://github.com/OCA/geospatial/actions/runs/11928567537/job/33245772449#step:8:100

thanks !

**Comment by lmignon** [comment]
> @lmignon could you retry ? the error is related to an error in a call of an unmocked external API. see : https://github.com/OCA/geospatial/actions/runs/11928567537/job/33245772449#step:8:100
> 
> thanks !

We should mock the call....

**Comment by legalsylvain** [comment]
> We should mock the call....

Arf. There are pro and cons that has been detailled in another Issue / PR. don't find right now the URL, but As far as I remember : Pro : CI is not failing randomly. Cons : we are not testing if the connection to the API works, but we are testing if an emulation of the API works, and API could have changed.
I have no clear point of view on that topic.

Note : 
- the error is on ``geoengine_base_geolocalize`` module that you are maintaining. 
- If I understand correctly, base_geolocalize core module is also related to that error. Not sure how we can mook a core test and we should do it.

Anyway, thanks for the merge  !

**Pull request merged**
