### PR TITLE
[11.0] mig geoengine base geolocalize

### PR DESCRIPTION
**Pull request by josueBulle**
Depends on geoengine_partner

- [x] #215

### CODE REVIEW

**Comment by josueBulle** [comment]
`Thanks a lot for your message. We confirm the reception of your Contributor License Agreement (CLA) for the Odoo Community Association (OCA) and Github login.`
29th Sept. 2019.
However, I changed the email address of my Github account since. Is that a problem ?

**Review by ecino — APPROVED** [review]
:+1: LGTM

**Comment by ecino** [comment]
Can you rebase the branch onto 11.0 ?

**Review by yvaucher — APPROVED** [review]

**Comment by yvaucher** [comment]
Thanks @josueBulle

**Pull request merged**
