### PR TITLE
Fix map render

### PR DESCRIPTION
**Pull request by igr-ok**
Fix map render - change timeout value.

### CODE REVIEW

**Review by legalsylvain — COMMENTED** [review]
Hi @igr-ok. Thanks for your PR !

Question : This look quite high, and can generate delay for end user. Did you tried something smaller, like 100 ? 

Technical : could you squash commits ? 

regards.

**Comment by igr-ok** [comment]
Hi @legalsylvain, yes  500ms too much, 100 is OK i cheked;

**Comment by legalsylvain** [comment]
Hi @igr-ok. Thanks could you change the value and squash commits ? thanks !

**Comment by igr-ok** [comment]
@legalsylvain, ok

**Pull request closed without merging**
