### PR TITLE
[MIG] base_geolocalize_openstreetmap: Migration to 12.0

### PR DESCRIPTION
**Pull request by len-foss**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
@len-foss 
image

**Comment by len-foss** [comment]
Hello @marcelsavegnago thanks for testing!
I don't think it's an issue: `geoengine.raster.layer` is defined in `base_geoengine`, which is not in the dependency tree of `base_geolocalize_openstreetmap` (its only dependency is `base_geolocalize`, in standard).
If you think there's a problem with the security rules you should probably open an issue related to that module.

**Comment by marcelsavegnago** [comment]
> Hello @marcelsavegnago thanks for testing!
> I don't think it's an issue: `geoengine.raster.layer` is defined in `base_geoengine`, which is not in the dependency tree of `base_geolocalize_openstreetmap` (its only dependency is `base_geolocalize`, in standard).
> If you think there's a problem with the security rules you should probably open an issue related to that module.

Hello @len-foss. Thanks for the feedback.

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by lmignon — APPROVED** [review]

**Pull request merged**
